server:
  port: ${PORT:8082}
  
logging:
  level: debug
  
spring:
  profiles: 
    active: default
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:alunodb
  h2:
    console:
      enabled: true    

management:
  security:
    enabled:  false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}